@port = 3002
@host = localhost:{{port}}
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDI1LTAxLTA2VDE3OjI3OjIzLjA1NDkzKzA3OjAwIiwidXNlcl9pZCI6MX0.1-83ch9WOjroGCqOEv2ynSo4nTJLUzc-5CQJGJrG58g
@user = users

###########
# CATEGORY #
###########
# Create
POST http://{{host}}/api/v1/categories HTTP/1.1
{{token}}
Content-Type: application/json

{"fullname":"Trang phục","code":"Cat002"}

###########
# Read
GET http://{{host}}/api/v1/categories/b08bbdef-551a-4e04-b78e-45aa4d4458ba HTTP/1.1
{{token}}
Content-Type: application/json

###########
# List
GET http://{{host}}/api/v1/categories HTTP/1.1
{{token}}
Content-Type: application/json

###########
# Update
PUT http://{{host}}/api/v1/categories/b08bbdef-551a-4e04-b78e-45aa4d4458ba HTTP/1.1
{{token}}
Content-Type: application/json

{"fullname":"Bàn ghế","code":"Cat003"}

###