@port = 3002
@host = localhost:{{port}}
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDI1LTAxLTA2VDE3OjI3OjIzLjA1NDkzKzA3OjAwIiwidXNlcl9pZCI6MX0.1-83ch9WOjroGCqOEv2ynSo4nTJLUzc-5CQJGJrG58g
@categories = categories
@category_id = b08bbdef-551a-4e04-b78e-45aa4d4458ba
@product_id = da8a7721-415d-4be0-a718-896906dc05e3

###########
# PRODUCT #
###########
# Create
POST http://{{host}}/api/v1/categories/{{category_id}}/products HTTP/1.1
{{token}}
Content-Type: application/json

{"fullname":"Bàn gỗ Tân Phú 2","code":"Product008"}

###########
# Read
GET http://{{host}}/api/v1/categories/{{category_id}}/products/{{product_id}} HTTP/1.1
{{token}}
Content-Type: application/json

###########
# List
GET http://{{host}}/api/v1/categories/{{category_id}}/products HTTP/1.1
{{token}}
Content-Type: application/json

###########
# Update
PUT http://{{host}}/api/v1/categories/{{category_id}}/products/{{product_id}} HTTP/1.1
{{token}}
Content-Type: application/json

{"fullname":"Bàn gỗ Becamex 2","code":"Product008"}

###

###########
# Delete
DELETE http://{{host}}/api/v1/categories/{{category_id}}/products/{{product_id}} HTTP/1.1
{{token}}
Content-Type: application/json

###